In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np.array([[x for x in range(2, 11, 2)], [y for y in range(1, 10, 2)]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [9]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [12]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [13]:
integers.dtype

dtype('int32')

In [14]:
floats.dtype

dtype('float64')

In [16]:
integers.ndim

2

In [17]:
floats.ndim

1

In [18]:
integers.shape

(2, 3)

In [19]:
floats.shape

(5,)

In [20]:
integers.size

6

In [21]:
integers.itemsize

4

In [22]:
floats.size

5

In [23]:
floats.itemsize

8

In [24]:
for row in integers:
    for column in row:
        print(column, end='  ')
    print()

1  2  3  
4  5  6  


In [25]:
for i in integers.flat:
    print(i, end='  ')

1  2  3  4  5  6  

In [26]:
a = np.array([[x for x in range(2, 11, 2)], [y for y in range(1, 10, 2)]])

In [27]:
a.ndim

2

In [28]:
a.shape

(2, 5)

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [36]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [37]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.linspace(0.0, 1.0)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [39]:
np.arange(1,21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [41]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [43]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [44]:
import random

%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 1000000)]

1.2 s ± 88.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [45]:
%timeit rolls_array = np.random.randint(1, 7, 6000000)

71.6 ms ± 7.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [46]:
%timeit rolls_array = np.random.randint(1, 7, 60000000)

721 ms ± 58.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [47]:
%timeit rolls_array = np.random.randint(1, 7, 600000000)

6.57 s ± 133 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [48]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6000000)

89.4 ms ± 9.88 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [50]:
%timeit sum([x for x in range(10_000_000)])

1.17 s ± 23.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [51]:
%timeit np.arange(10_000_000).sum()

24 ms ± 1.76 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [61]:
numbers = np.arange(1, 6)

In [53]:
numbers

array([1, 2, 3, 4, 5])

In [54]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [55]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [62]:
numbers

array([1, 2, 3, 4, 5])

In [63]:
numbers += 10

In [64]:
numbers

array([11, 12, 13, 14, 15])

In [65]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [66]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [67]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [68]:
numbers

array([11, 12, 13, 14, 15])

In [69]:
numbers >= 13

array([False, False,  True,  True,  True])

In [70]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [71]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [72]:
numbers == numbers2

array([False, False, False, False, False])

In [73]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [74]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [75]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [76]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [77]:
grades.sum()

1054

In [78]:
grades.min()

70

In [79]:
grades.max()

100

In [80]:
grades.mean()

87.83333333333333

In [81]:
grades.std()

8.792357792739987

In [82]:
grades.var()

77.30555555555556

In [83]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [84]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [86]:
grades = np.random.randint(60, 101, 12).reshape(3,4)

In [87]:
grades

array([[65, 83, 91, 68],
       [98, 73, 78, 70],
       [61, 63, 89, 60]])

In [88]:
grades.mean()

74.91666666666667

In [89]:
grades.mean(axis=0)

array([74.66666667, 73.        , 86.        , 66.        ])

In [90]:
grades.mean(axis=1)

array([76.75, 79.75, 68.25])

In [91]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [92]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [93]:
numbers2 = np.arange(1, 7) *10

In [94]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [95]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [96]:
numbers + numbers2

array([11, 24, 39, 56, 75, 96])

In [97]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [98]:
numbers3 = numbers2.reshape(2, 3)

In [99]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [100]:
numbers4 = np.array([2, 4, 6])

In [101]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [102]:
numbers = np.arange(1, 6)

In [103]:
np.power(numbers, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [104]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [105]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [106]:
grades[0, 1]

96

In [107]:
grades[1]

array([100,  87,  90])

In [108]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [109]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [110]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [111]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [112]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [114]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8 , 9, 10], [11, 12, 13, 14, 15]])

In [116]:
a[1]

array([ 6,  7,  8,  9, 10])

In [117]:
a[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [119]:
a[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [120]:
numbers = np.arange(1, 6)

In [121]:
numbers

array([1, 2, 3, 4, 5])

In [122]:
numbers2 = numbers.view()

In [123]:
numbers2

array([1, 2, 3, 4, 5])

In [126]:
print(id(numbers))
print(id(numbers2))

2644465261424
2644465261712


In [127]:
numbers[1] *= 10

In [128]:
numbers2

array([ 1, 20,  3,  4,  5])

In [129]:
numbers

array([ 1, 20,  3,  4,  5])

In [130]:
numbers2[1] /=10

In [131]:
numbers

array([1, 2, 3, 4, 5])

In [132]:
numbers2

array([1, 2, 3, 4, 5])

In [133]:
numbers2 = numbers[0:3]

In [134]:
numbers2

array([1, 2, 3])

In [135]:
id(numbers)

2644465261424

In [136]:
id(numbers2)

2644465232464

In [137]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [138]:
numbers[1] *= 20

In [139]:
numbers

array([ 1, 40,  3,  4,  5])

In [140]:
numbers2

array([ 1, 40,  3])

In [141]:
numbers = np.arange(1, 6)

In [142]:
numbers

array([1, 2, 3, 4, 5])

In [143]:
numbers2 = numbers.copy()

In [144]:
numbers2

array([1, 2, 3, 4, 5])

In [145]:
numbers[1] *= 10

In [146]:
numbers

array([ 1, 20,  3,  4,  5])

In [147]:
numbers2

array([1, 2, 3, 4, 5])

In [148]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [149]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [150]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [151]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [152]:
grades.resize(1, 6)

In [153]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [154]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [155]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [156]:
flattened = grades.flatten()

In [157]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [158]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [159]:
flattened[0] = 100

In [160]:
flattened

array([100,  96,  70, 100,  87,  90])

In [161]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [162]:
raveled = grades.ravel()

In [163]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [164]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [165]:
raveled[0] = 100

In [166]:
raveled

array([100,  96,  70, 100,  87,  90])

In [167]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [168]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [169]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [170]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [171]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [172]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [173]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [177]:
a = np.hstack((a,a))

In [178]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [179]:
a = np.vstack((a,a))

In [180]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [181]:
import pandas as pd

In [182]:
grades = pd.Series([87, 100, 94])

In [183]:
grades

0     87
1    100
2     94
dtype: int64

In [184]:
pd.Series(98.6, range(3))

0    98.6
1    98.6
2    98.6
dtype: float64

In [185]:
grades[0]

87

In [186]:
grades.count()

3

In [187]:
grades.mean()

93.66666666666667

In [188]:
grades.min()

87

In [189]:
grades.max()

100

In [190]:
grades.std()

6.506407098647712

In [191]:
grades.describe()

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [192]:
grades = pd.Series([87, 100, 94], index=['Wally', 'Eva', 'Sam'])

In [193]:
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [194]:
grades = pd.Series({'Wally': 87, 'Eva': 100, 'Sam': 94})

In [195]:
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [196]:
grades['Eva']

100

In [197]:
grades.Wally

87

In [198]:
grades.dtype

dtype('int64')

In [199]:
grades.values

array([ 87, 100,  94], dtype=int64)

In [200]:
hardware = pd.Series(['Hammer', 'Saw', 'Wrench'])

In [201]:
hardware

0    Hammer
1       Saw
2    Wrench
dtype: object

In [202]:
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [203]:
hardware.str.upper()

0    HAMMER
1       SAW
2    WRENCH
dtype: object

In [204]:
temps = np.random.randint(60, 101, 6)

In [205]:
temperatures = pd.Series(temps)

In [206]:
temperatures

0    73
1    74
2    87
3    88
4    99
5    85
dtype: int32

In [207]:
temperatures.min() 

73

In [209]:
temperatures.max()

99

In [210]:
temperatures.describe()

count     6.000000
mean     84.333333
std       9.709102
min      73.000000
25%      76.750000
50%      86.000000
75%      87.750000
max      99.000000
dtype: float64

In [212]:
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90],
               'Sam': [94, 77, 90], 'Katie': [100, 81, 82],
               'Bob': [83, 65, 85]}

In [213]:
grades = pd.DataFrame(grades_dict)

In [214]:
grades

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [215]:
grades.index = ['Test1', 'Test2', 'Test3']

In [216]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [217]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [218]:
grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64

In [219]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [220]:
grades.iloc[1]

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [221]:
grades.loc['Test1':'Test3']

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [222]:
grades.iloc[0:2]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

In [223]:
grades.loc[['Test1', 'Test3']]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [224]:
grades.iloc[[0, 2]]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [225]:
grades.loc['Test1':'Test2', ['Eva', 'Katie']]

Eva  Katie
Test1  100    100
Test2   87     81

In [226]:
grades.iloc[[0, 2], 0:3]

Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

In [227]:
grades[grades >= 90]

Wally    Eva   Sam  Katie  Bob
Test1    NaN  100.0  94.0  100.0  NaN
Test2   96.0    NaN   NaN    NaN  NaN
Test3    NaN   90.0  90.0    NaN  NaN

In [228]:
grades[(grades >= 80) & (grades < 90)]

Wally   Eva  Sam  Katie   Bob
Test1   87.0   NaN  NaN    NaN  83.0
Test2    NaN  87.0  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

In [231]:
grades.at['Test2', 'Eva']

87

In [232]:
grades.iat[2, 0]

70

In [233]:
grades.at['Test2', 'Eva'] = 100

In [234]:
grades.at['Test2', 'Eva']

100

In [235]:
grades.iat[1, 2] = 87

In [236]:
grades.iat[1, 2]

87

In [237]:
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   96.666667  90.333333   87.666667  77.666667
std    13.203535    5.773503   3.511885   10.692677  11.015141
min    70.000000   90.000000  87.000000   81.000000  65.000000
25%    78.500000   95.000000  88.500000   81.500000  74.000000
50%    87.000000  100.000000  90.000000   82.000000  83.000000
75%    91.500000  100.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [238]:
pd.set_option('precision', 2)

In [239]:
grades.describe()

Wally     Eva    Sam   Katie    Bob
count   3.00    3.00   3.00    3.00   3.00
mean   84.33   96.67  90.33   87.67  77.67
std    13.20    5.77   3.51   10.69  11.02
min    70.00   90.00  87.00   81.00  65.00
25%    78.50   95.00  88.50   81.50  74.00
50%    87.00  100.00  90.00   82.00  83.00
75%    91.50  100.00  92.00   91.00  84.00
max    96.00  100.00  94.00  100.00  85.00

In [240]:
grades.mean()

Wally    84.33
Eva      96.67
Sam      90.33
Katie    87.67
Bob      77.67
dtype: float64

In [241]:
grades.T

Test1  Test2  Test3
Wally     87     96     70
Eva      100    100     90
Sam       94     87     90
Katie    100     81     82
Bob       83     65     85

In [242]:
grades.T.describe()

Test1   Test2  Test3
count    5.00    5.00   5.00
mean    92.80   85.80  83.40
std      7.66   13.81   8.23
min     83.00   65.00  70.00
25%     87.00   81.00  82.00
50%     94.00   87.00  85.00
75%    100.00   96.00  90.00
max    100.00  100.00  90.00

In [244]:
grades.T.mean()

Test1    92.8
Test2    85.8
Test3    83.4
dtype: float64

In [246]:
grades.sort_index(ascending=False)

Wally  Eva  Sam  Katie  Bob
Test3     70   90   90     82   85
Test2     96  100   87     81   65
Test1     87  100   94    100   83

In [247]:
grades.sort_index(axis=1)

Bob  Eva  Katie  Sam  Wally
Test1   83  100    100   94     87
Test2   65  100     81   87     96
Test3   85   90     82   90     70

In [248]:
grades.sort_values(by='Test1', axis=1, ascending=False)

Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2  100     81   87     96   65
Test3   90     82   90     70   85

In [250]:
grades.T.sort_values(by='Test1', ascending=False)

Test1  Test2  Test3
Eva      100    100     90
Katie    100     81     82
Sam       94     87     90
Wally     87     96     70
Bob       83     65     85

In [251]:
grades.loc['Test1'].sort_values(ascending=False)

Eva      100
Katie    100
Sam       94
Wally     87
Bob       83
Name: Test1, dtype: int64

In [252]:
temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82],
         'Thu': [75, 97], 'Fri': [62, 79]}

In [253]:
temperatures = pd.DataFrame(temps, index=['Low', 'High'])

In [254]:
temperatures

Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79

In [256]:
temperatures.loc[:, 'Mon':'Wed']

Mon  Tue  Wed
Low    68   71   66
High   89   93   82

In [257]:
temperatures.loc['Low']

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64

In [258]:
pd.set_option('precision', 2)

In [259]:
temperatures.mean()

Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64

In [260]:
temperatures.T.mean()

Low     68.4
High    88.0
dtype: float64